### ISSUE TITLE
Discovery and MUC with Sharp XMPP

### ISSUE THREAD

**Issue by sbsrouteur** [pgstath/Sharp.Xmpp#1]
How does one with S22.Xmpp use the service discovery to list the available chatrooms, and then how does one join such a chat room?

Could not find a sample for that.

**Comment by pgstath** [comment]
Unfortunately Sharp.Xmpp does not support for the time being MUC (XEP-0045, http://xmpp.org/extensions/xep-0045.html) and its not on the immediate roadmap, however I could provide any help needed if someone decided to implement that.

**Comment by sbsrouteur** [comment]
Thanks for the feed back. I was able to find another lib that does the MUC for me. Good luck with S22. It's by far the easiest to start with. But it lacks some major features (IMHO).

**Comment by yon86** [comment]
@sbsrouteur what other library are u using thanks
