### ISSUE TITLE
Sharp sample code is not sending message

### ISSUE THREAD

**Issue by rashkat** [pgstath/Sharp.Xmpp#11]
Hello 
I just started using sharp. I was trying to run a sample code however I am not able to send any message through this one. I am able to receive messages though. 

Code runs absolutely without error but no message got sent. I have tried to debug the code and doubt on following code from Sharp.Xmpp.Im.XmppIm class

public void SendMessage(Message message) {
			AssertValid();
			message.ThrowIfNull("message");
			// "Stamp" the sender's JID onto the message. 
			message.From = Jid;
			// Invoke IOutput<Message> Plugins.
			foreach (var ext in extensions) {
				var filter = ext as IOutputFilter<Message>;
				if (filter != null)
					filter.Output(message); ################ control never goes to this line. so I think there is no ext available for IOutputFilter<Message> ?? I am not sure though as core.SendMessage works fine. I am pretty new to XMPP world so please bare with me if its a silly question.... ################
			}
			core.SendMessage(message);
		}

Early help/reply is appreciable as I need to decide on opensource c# xmpp library as soon as possible.

Regards,
Rashmi

**Comment by rashkat** [comment]
Hey I am able to send message. I was using rashmi as jid whereas it needs full user name like rashmi@serverhost.com

Thanks anyways. I would be requiring lot of help in this journey, hope can go ahead with this one. 

Wish you and your team a very Happy New Year 2016 ahead!!

cheers
Rashmi

**Comment by pgstath** [comment]
Hi @rashkat , Happy new year, I will be around to help if I can:)!
