### ISSUE TITLE
Problem in changing password/ how to make use of in-built registration for this purpose

### ISSUE THREAD

**Issue by ismanoor** [pgstath/Sharp.Xmpp#47]
hi... 
I'm trying to change password of a user registered at openfire using sharp.xmpp 
but i couldn't find any direct method available for this purpose.
whereas there are internal inbuilt-registration functionalities available like change password/register.
Can you please help me how to use xmppclient object to change password 

Thanks in advance!

**Comment by ismanoor** [comment]
@pgstath ???

**Comment by akoepe** [comment]
Hy! I downloaded the library and added a few lines...(Creators might have forgotten to add this one I don't know)

1.Open XMPPClient.cs
2.Search for the Register method
3.Create a copy of it
4.Call it ChangePassword, parameter should be a string, inside the method change the Register function to ChangePassword.

Should look like this:

public void ChangePassword(string NewPassword)
        {
            NewPassword.ThrowIfNull("callback");
            inBandRegistration.ChangePassword(NewPassword);
        }

Now you can simply call this on a Connected!!! user and it will change the password.
