### ISSUE TITLE
NuGet package update

### ISSUE THREAD

**Issue by DavePilks** [pgstath/Sharp.Xmpp#6]
When was the last time that the package was updated on NuGet?  When I try and add it to my app, I get this.

"Could not install package 'S22.Xmpp 1.0.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v4.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Is there a work-around that I can use to get this working?

**Comment by pgstath** [comment]
The latest version is  1.0.2.1 (28/3/2015). Can you provide information on your environment? 
You can also download the S22 source, and include it on your project, in order to test it.

**Comment by DavePilks** [comment]
I am trying to add it to a Xamarin ANdroid project.

**Comment by pgstath** [comment]
Clone the latest source code from GIT, download it and add it a project to your solution.

**Comment by DavePilks** [comment]
It does not let me add a reference to the project. It gives the following error message "Incompatible target framework"

**Comment by pgstath** [comment]
I have confirmed the issue for an Android Xamarin project, while the package is added the references are not updated. However, I can add the reference from the package source directly. Probably its an issue with the configuration of the package.

**Comment by saggy** [comment]
HI,

I am trying same this project in xamarin android, to implement in XMPP Chat, and i am facing the same issue as @pgstath  facing.

Is there is any solution of this problem, but it work if i used old version of  "ARSoft.tool.Net" Nuget.
But as i trying to update it doesn't install , and i am failed.
Pls help me to solve this problem, any help will be appreciated.

**Comment by pgstath** [comment]
Hi @saggy 
So you have installed the package but it is not updated? Please provide some additional information. Have you tried downloading the source code and including it in your Solution as a separate project? It is not the most elegant solution, but please try.
Also you should check your project's references, to include Sharp.Xmpp
